In [1]:
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

import pickle


#read dataset
dataset = pd.read_csv('diabetes.csv')
dataset.tail(15)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
753,0,181,88,44,510,43.3,0.222,26,1
754,8,154,78,32,0,32.4,0.443,45,1
755,1,128,88,39,110,36.5,1.057,37,1
756,7,137,90,41,0,32.0,0.391,39,0
757,0,123,72,0,0,36.3,0.258,52,1
758,1,106,76,0,0,37.5,0.197,26,0
759,6,190,92,0,0,35.5,0.278,66,1
760,2,88,58,26,16,28.4,0.766,22,0
761,9,170,74,31,0,44.0,0.403,43,1
762,9,89,62,0,0,22.5,0.142,33,0
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [2]:
(dataset == 0).sum()

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                     500
dtype: int64

In [3]:

mean_bmi = dataset['BMI'].mean(skipna=True)
dataset.loc[dataset.BMI == 0, 'BMI'] = mean_bmi



mean_Glucose = dataset['Glucose'].mean(skipna=True)
dataset.loc[dataset.Glucose == 0, 'Glucose'] = mean_Glucose

mean_BloodPressure = dataset['BloodPressure'].mean(skipna=True)
dataset.loc[dataset.BloodPressure == 0, 'BloodPressure'] = mean_BloodPressure



# mean_Insulin = dataset['Insulin'].mean(skipna=True)
# dataset.loc[dataset.Insulin == 0, 'Insulin'] = mean_Insulin

In [4]:
(dataset == 0).sum()

Pregnancies                 111
Glucose                       0
BloodPressure                 0
SkinThickness               227
Insulin                     374
BMI                           0
DiabetesPedigreeFunction      0
Age                           0
Outcome                     500
dtype: int64

In [5]:
#make input(X) and output(Y)
X = dataset[['Glucose','BloodPressure','BMI','DiabetesPedigreeFunction']]
Y = dataset.iloc[:,  -1]

In [6]:
X.head(15)
X.tail(15)

     Glucose  BloodPressure   BMI  DiabetesPedigreeFunction
753    181.0           88.0  43.3                     0.222
754    154.0           78.0  32.4                     0.443
755    128.0           88.0  36.5                     1.057
756    137.0           90.0  32.0                     0.391
757    123.0           72.0  36.3                     0.258
758    106.0           76.0  37.5                     0.197
759    190.0           92.0  35.5                     0.278
760     88.0           58.0  28.4                     0.766
761    170.0           74.0  44.0                     0.403
762     89.0           62.0  22.5                     0.142
763    101.0           76.0  32.9                     0.171
764    122.0           70.0  36.8                     0.340
765    121.0           72.0  26.2                     0.245
766    126.0           60.0  30.1                     0.349
767     93.0           70.0  30.4                     0.315

In [7]:
#find missing values
dataset.isnull().sum(axis=0)
dataset.head(15)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.000000,35,0,33.600000,0.627,50,1
1,1,85.0,66.000000,29,0,26.600000,0.351,31,0
2,8,183.0,64.000000,0,0,23.300000,0.672,32,1
3,1,89.0,66.000000,23,94,28.100000,0.167,21,0
4,0,137.0,40.000000,35,168,43.100000,2.288,33,1
5,5,116.0,74.000000,0,0,25.600000,0.201,30,0
6,3,78.0,50.000000,32,88,31.000000,0.248,26,1
7,10,115.0,69.105469,0,0,35.300000,0.134,29,0
8,2,197.0,70.000000,45,543,30.500000,0.158,53,1
9,8,125.0,96.000000,0,0,31.992578,0.232,54,1
10,4,110.0,92.000000,0,0,37.600000,0.191,30,0
11,10,168.0,74.000000,0,0,38.000000,0.537,34,1
12,10,139.0,80.000000,0,0,27.100000,1.441,57,0
13,1,189.0,60.000000,23,846,30.100000,0.398,59,1
14,5,166.0,72.000000,19,175,25.800000,0.587,51,1

In [8]:
from sklearn.preprocessing import MinMaxScaler
mmScaler=MinMaxScaler(feature_range=(0,1))
rescaleX=mmScaler.fit_transform(X)
rescaleX

array([[0.67096774, 0.48979592, 0.31492843, 0.23441503],
       [0.26451613, 0.42857143, 0.17177914, 0.11656704],
       [0.89677419, 0.40816327, 0.10429448, 0.25362938],
       ...,
       [0.49677419, 0.48979592, 0.16359918, 0.07130658],
       [0.52903226, 0.36734694, 0.24335378, 0.11571307],
       [0.31612903, 0.46938776, 0.24948875, 0.10119556]])

In [9]:
X[:].mean()
X[:].std()
from sklearn.preprocessing import StandardScaler
sScaler=StandardScaler()
reScaleX=sScaler.fit_transform(X)
reScaleX
reScaleX[:,0].mean()
reScaleX[:,0].std()

1.0

In [10]:
from sklearn.preprocessing import Normalizer
norm=Normalizer()
norm.fit_transform(X)

array([[0.88105613, 0.4286219 , 0.20002355, 0.00373258],
       [0.76677201, 0.59537591, 0.23995454, 0.00316632],
       [0.93718889, 0.32776005, 0.11932514, 0.00344148],
       ...,
       [0.84486372, 0.50272882, 0.18293743, 0.00171067],
       [0.88256305, 0.42026812, 0.21083451, 0.00244456],
       [0.7730361 , 0.58185513, 0.25269137, 0.00261835]])

In [12]:
from sklearn.preprocessing import Binarizer
bina=Binarizer(threshold=5).fit(X)
bina.fit_transform(X)

array([[1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.],
       ...,
       [1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.]])

In [13]:
X.head(15)

    Glucose  BloodPressure        BMI  DiabetesPedigreeFunction
0     148.0      72.000000  33.600000                     0.627
1      85.0      66.000000  26.600000                     0.351
2     183.0      64.000000  23.300000                     0.672
3      89.0      66.000000  28.100000                     0.167
4     137.0      40.000000  43.100000                     2.288
5     116.0      74.000000  25.600000                     0.201
6      78.0      50.000000  31.000000                     0.248
7     115.0      69.105469  35.300000                     0.134
8     197.0      70.000000  30.500000                     0.158
9     125.0      96.000000  31.992578                     0.232
10    110.0      92.000000  37.600000                     0.191
11    168.0      74.000000  38.000000                     0.537
12    139.0      80.000000  27.100000                     1.441
13    189.0      60.000000  30.100000                     0.398
14    166.0      72.000000  25.800000                     0.587

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y,train_size=0.8)

In [15]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [16]:
y_predicted = model.predict(X_test)

In [17]:
model.predict_proba(X_test)

array([[0.60227785, 0.39772215],
       [0.83774931, 0.16225069],
       [0.2986246 , 0.7013754 ],
       [0.48737887, 0.51262113],
       [0.85935261, 0.14064739],
       [0.83572334, 0.16427666],
       [0.92229979, 0.07770021],
       [0.73438323, 0.26561677],
       [0.85891528, 0.14108472],
       [0.18070173, 0.81929827],
       [0.53210179, 0.46789821],
       [0.77644782, 0.22355218],
       [0.83052462, 0.16947538],
       [0.461279  , 0.538721  ],
       [0.66591641, 0.33408359],
       [0.94189449, 0.05810551],
       [0.95980064, 0.04019936],
       [0.61623848, 0.38376152],
       [0.94646809, 0.05353191],
       [0.78224192, 0.21775808],
       [0.63326067, 0.36673933],
       [0.55466353, 0.44533647],
       [0.83040272, 0.16959728],
       [0.79780184, 0.20219816],
       [0.60754023, 0.39245977],
       [0.88976792, 0.11023208],
       [0.16257719, 0.83742281],
       [0.11699383, 0.88300617],
       [0.19003015, 0.80996985],
       [0.78662956, 0.21337044],
       [0.92660368, 0.07339632],
       [0.13064766, 0.86935234],
       [0.59534589, 0.40465411],
       [0.29256828, 0.70743172],
       [0.962552  , 0.037448  ],
       [0.27572754, 0.72427246],
       [0.82912101, 0.17087899],
       [0.86792181, 0.13207819],
       [0.91130211, 0.08869789],
       [0.83566747, 0.16433253],
       [0.93804625, 0.06195375],
       [0.86021899, 0.13978101],
       [0.88391224, 0.11608776],
       [0.799174  , 0.200826  ],
       [0.85139035, 0.14860965],
       [0.540359  , 0.459641  ],
       [0.27672322, 0.72327678],
       [0.71945539, 0.28054461],
       [0.86072817, 0.13927183],
       [0.68808761, 0.31191239],
       [0.53440842, 0.46559158],
       [0.64126001, 0.35873999],
       [0.71909879, 0.28090121],
       [0.72327855, 0.27672145],
       [0.84849172, 0.15150828],
       [0.87802021, 0.12197979],
       [0.74293887, 0.25706113],
       [0.56074901, 0.43925099],
       [0.82561867, 0.17438133],
       [0.72107926, 0.27892074],
       [0.0663998 , 0.9336002 ],
       [0.98087312, 0.01912688],
       [0.16824655, 0.83175345],
       [0.55211562, 0.44788438],
       [0.83298552, 0.16701448],
       [0.07671627, 0.92328373],
       [0.31658377, 0.68341623],
       [0.44976343, 0.55023657],
       [0.73491848, 0.26508152],
       [0.94301887, 0.05698113],
       [0.25643851, 0.74356149],
       [0.90051109, 0.09948891],
       [0.71268196, 0.28731804],
       [0.66658378, 0.33341622],
       [0.8859673 , 0.1140327 ],
       [0.38623586, 0.61376414],
       [0.35950785, 0.64049215],
       [0.656871  , 0.343129  ],
       [0.48407713, 0.51592287],
       [0.62256118, 0.37743882],
       [0.8526846 , 0.1473154 ],
       [0.87413671, 0.12586329],
       [0.79223856, 0.20776144],
       [0.60413948, 0.39586052],
       [0.9463427 , 0.0536573 ],
       [0.95760485, 0.04239515],
       [0.52844777, 0.47155223],
       [0.91409237, 0.08590763],
       [0.42135886, 0.57864114],
       [0.53903199, 0.46096801],
       [0.6441696 , 0.3558304 ],
       [0.72644673, 0.27355327],
       [0.07028447, 0.92971553],
       [0.22908744, 0.77091256],
       [0.67217539, 0.32782461],
       [0.1932825 , 0.8067175 ],
       [0.8033181 , 0.1966819 ],
       [0.90021476, 0.09978524],
       [0.75778538, 0.24221462],
       [0.13476978, 0.86523022],
       [0.94766314, 0.05233686],
       [0.91739749, 0.08260251],
       [0.91362155, 0.08637845],
       [0.86502198, 0.13497802],
       [0.78383349, 0.21616651],
       [0.68925253, 0.31074747],
       [0.85375667, 0.14624333],
       [0.16214724, 0.83785276],
       [0.81750481, 0.18249519],
       [0.91522931, 0.08477069],
       [0.77099355, 0.22900645],
       [0.58262173, 0.41737827],
       [0.82680891, 0.17319109],
       [0.77045457, 0.22954543],
       [0.90072034, 0.09927966],
       [0.13054791, 0.86945209],
       [0.7269041 , 0.2730959 ],
       [0.16476764, 0.83523236],
       [0.31100953, 0.68899047],
       [0.2018716 , 0.7981284 ],
       [0.31357719, 0.68642281],
       [0.58188363, 0.41811637],
       [0.97014796, 0.02985204],
       [0.8540452 , 0.1459548 ],
       [0.61376164, 0.38623836],
       [0.89274413, 0.10725587],
       [0.2271679 , 0.7728321 ],
       [0.7119725 , 0.2880275 ],
       [0.68591436, 0.31408564],
       [0.15755223, 0.84244777],
       [0.91252197, 0.08747803],
       [0.63632184, 0.36367816],
       [0.79412941, 0.20587059],
       [0.73601246, 0.26398754],
       [0.89160476, 0.10839524],
       [0.94765977, 0.05234023],
       [0.92337966, 0.07662034],
       [0.77752868, 0.22247132],
       [0.74233047, 0.25766953],
       [0.75254294, 0.24745706],
       [0.48925396, 0.51074604],
       [0.19330409, 0.80669591],
       [0.66783595, 0.33216405],
       [0.56494062, 0.43505938],
       [0.96641702, 0.03358298],
       [0.92592303, 0.07407697],
       [0.56778434, 0.43221566],
       [0.54115396, 0.45884604],
       [0.85155677, 0.14844323],
       [0.74965373, 0.25034627],
       [0.80274402, 0.19725598],
       [0.3946994 , 0.6053006 ],
       [0.57730832, 0.42269168],
       [0.47209508, 0.52790492]])

In [18]:
model.score(X_test,y_test)

0.7792207792207793

In [21]:
print(model.predict([[137,40,32,0.391]]))

[0]